$PROTEIN= join"",qw(
MAVRRRTSNVFTCFNDEQISEMRDAFGLFDIDGDCVVTEENLKEFCKSIGDPFTDEEIKAMIGEISPNCN
 FMMFLSVLGDKLSQVSELQKILTNFKVLDEGNKGTINKEYLRKVLSETEDKEFEDLVKGCVKNGEVDYNR
 LAIKIKHGEILENLLVQEE
);
print $PROTEIN,"\n";
$hydrophobic=($PROTEIN=~tr/GAVLIPFMWC//);
$percentage=100*($hydrophobic/length($PROTEIN));
print "The percentage of hydrophobic residues = $percentage%\n";
exit;